[app]
name = "todo-go"
env = "production"

[database]
host = "localhost"
port = 5432
user = "postgres"
password = "postgres"
name = "taskdb-go"

[logging]
level = "info"        # debug, info, warn, error
dynamic = true        # allow runtime changes (default true)

[jwt]
secret = "super-secret-key"

[server]
port = 8080
